# Generated by Django 4.2.7 on 2025-09-28 17:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("color", models.CharField(default="#007bff", max_length=7)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="problems.problemcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Problem Category",
                "verbose_name_plural": "Problem Categories",
                "db_table": "problem_categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProblemTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("color", models.CharField(default="#6c757d", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Problem Tag",
                "verbose_name_plural": "Problem Tags",
                "db_table": "problem_tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProblemTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "template_data",
                    models.JSONField(
                        help_text="Complete problem template including question, variables, solution"
                    ),
                ),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="problems.problemcategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Problem Template",
                "verbose_name_plural": "Problem Templates",
                "db_table": "problem_templates",
                "ordering": ["-usage_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(help_text="Brief description of the problem"),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                (
                    "question_text",
                    models.TextField(
                        help_text="Problem statement with LaTeX formatting"
                    ),
                ),
                (
                    "question_latex",
                    models.TextField(
                        blank=True, help_text="Pre-rendered LaTeX for question"
                    ),
                ),
                (
                    "solution_expression",
                    models.TextField(help_text="Correct answer in LaTeX format"),
                ),
                (
                    "solution_explanation",
                    models.TextField(
                        blank=True, help_text="Step-by-step solution explanation"
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        default=dict,
                        help_text="Variable definitions: {var_name: {min: val, max: val, type: 'int'|'float', step: val}}",
                    ),
                ),
                (
                    "answer_tolerance",
                    models.FloatField(
                        default=1e-06,
                        help_text="Numerical tolerance for answer checking",
                        validators=[
                            django.core.validators.MinValueValidator(1e-12),
                            django.core.validators.MaxValueValidator(0.1),
                        ],
                    ),
                ),
                (
                    "allow_equivalent_forms",
                    models.BooleanField(
                        default=True,
                        help_text="Allow mathematically equivalent expressions",
                    ),
                ),
                ("has_multiple_parts", models.BooleanField(default=False)),
                (
                    "total_parts",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "problem_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="problem_images/"
                    ),
                ),
                ("supplementary_files", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "is_template",
                    models.BooleanField(
                        default=False,
                        help_text="Can be used as template for new problems",
                    ),
                ),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("average_difficulty_rating", models.FloatField(default=0.0)),
                ("success_rate", models.FloatField(default=0.0)),
                ("average_solve_time", models.FloatField(default=0.0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_problems",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="problems.problemcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Problem",
                "verbose_name_plural": "Problems",
                "db_table": "problems",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProblemTagging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems.problem",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems.problemtag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Problem Tagging",
                "verbose_name_plural": "Problem Taggings",
                "db_table": "problem_tagging",
                "unique_together": {("problem", "tag")},
            },
        ),
        migrations.CreateModel(
            name="ProblemPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_number",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "part_text",
                    models.TextField(help_text="Text for this specific part"),
                ),
                (
                    "expected_answer",
                    models.TextField(
                        help_text="Expected answer for this part in LaTeX"
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("allow_partial_credit", models.BooleanField(default=True)),
                (
                    "answer_format",
                    models.CharField(
                        choices=[
                            ("expression", "Mathematical Expression"),
                            ("numeric", "Numeric Value"),
                            ("multiple_choice", "Multiple Choice"),
                            ("true_false", "True/False"),
                        ],
                        default="expression",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Problem Part",
                "verbose_name_plural": "Problem Parts",
                "db_table": "problem_parts",
                "ordering": ["problem", "part_number"],
                "unique_together": {("problem", "part_number")},
            },
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(
                fields=["category", "difficulty"], name="problems_categor_bb78f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(
                fields=["author", "is_published"], name="problems_author__833187_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(
                fields=["is_published", "created_at"],
                name="problems_is_publ_56ed40_idx",
            ),
        ),
    ]
