# Generated by Django 6.0.4 on 2026-04-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_probleminstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='variables',
            field=models.JSONField(blank=True, default=dict, help_text="Variable definitions: {var_name: {min: val, max: val, type: 'int'|'float', step: val}}"),
        ),
    ]
