# Generated by Django 4.2.7 on 2026-04-03 03:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='enrolled_courses', through='quizzes.CourseEnrollment', to=settings.AUTH_USER_MODEL),
        ),
    ]
