# Generated by Django 4.2.7 on 2026-04-08 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_course_enrolled_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_number', models.PositiveIntegerField()),
                ('box_label', models.CharField(blank=True, max_length=100)),
                ('placeholder_text', models.CharField(blank=True, max_length=200)),
                ('expected_answer', models.TextField()),
                ('allow_approximation', models.BooleanField(default=False)),
                ('approximation_tolerance', models.FloatField(blank=True, null=True)),
                ('points', models.FloatField(default=1.0)),
                ('quiz_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_boxes', to='quizzes.quizproblem')),
            ],
            options={
                'verbose_name': 'Answer Box',
                'verbose_name_plural': 'Answer Boxes',
                'db_table': 'answer_boxes',
                'ordering': ['box_number'],
                'unique_together': {('quiz_problem', 'box_number')},
            },
        ),
        migrations.CreateModel(
            name='AnswerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.TextField()),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True)),
                ('points_earned', models.FloatField(default=0.0)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('answer_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.answerbox')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_submissions', to='quizzes.quizattempt')),
            ],
            options={
                'verbose_name': 'Answer Submission',
                'verbose_name_plural': 'Answer Submissions',
                'db_table': 'answer_submissions',
                'ordering': ['submitted_at'],
                'unique_together': {('attempt', 'answer_box')},
            },
        ),
    ]
