# Generated by Django 4.2.7 on 2026-04-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_answerbox_answersubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerbox',
            name='answer_template',
            field=models.TextField(blank=True, help_text="LaTeX template with [BLANK] markers, e.g., '\\Omega_p = \\int [BLANK] d\\Omega'"),
        ),
        migrations.AddField(
            model_name='answerbox',
            name='is_readonly',
            field=models.BooleanField(default=False, help_text="If true, show answer but don't allow editing"),
        ),
    ]
